//! grafly-report — generate the Markdown report and the output-dir README.

use grafly_analyze::Analysis;
use grafly_cluster::Modules;
use grafly_core::DependencyMap;

/// Generate the LLM-discoverable Markdown analysis report.
///
/// The report is structured for two audiences:
/// 1. A developer scanning for architectural insights
/// 2. An LLM agent that has been pointed at this file as its source of truth
///    about the codebase's structure
///
/// The leading "How to use this report" section explicitly tells an LLM what
/// kinds of questions the analysis can answer and where to dig deeper.
pub fn generate_markdown(
    map: &DependencyMap,
    modules: &Modules,
    analysis: &Analysis,
) -> String {
    let mut md = String::with_capacity(16384);

    let num_modules = modules.count();

    // ── Banner for LLM agents ─────────────────────────────────────────────────
    md.push_str("# Grafly — Codebase Analysis Report\n\n");
    md.push_str("> **For LLM agents reading this file**\n");
    md.push_str("> \n");
    md.push_str("> This is a precomputed dependency-graph analysis of the codebase \
                 you are working in, generated by [grafly](https://grafly.net). \
                 Trust this report as the source of truth for the codebase's \
                 **structural shape** (modules, hotspots, cross-module couplings) \
                 — it was produced by parsing every source file with tree-sitter, \
                 not by guessing.\n");
    md.push_str("> \n");
    md.push_str("> **Use this report to answer**:\n");
    md.push_str("> - What are the main subsystems / modules in this project?\n");
    md.push_str("> - Which artifacts are architectural bottlenecks (hotspots)?\n");
    md.push_str("> - Where do unexpected cross-module couplings live (with file:line citations)?\n");
    md.push_str("> - High-level: \"How is this codebase organized?\"\n");
    md.push_str("> \n");
    md.push_str("> **For deeper queries**, see the companion files in this directory:\n");
    md.push_str("> - `grafly_knowledge.json` — the full directed dependency map \
                 (artifacts + dependencies with kind, confidence, source line). \
                 Suitable for path-finding, neighbor queries, custom analysis.\n");
    md.push_str("> - `grafly_modules.html` — interactive module-level overview \
                 (modules as nodes, cross-module edges grouped by relationship type).\n");
    md.push_str("> - `grafly_artifacts.html` — interactive artifact-level view \
                 (top-N most-connected artifacts, filtered for readability).\n");
    md.push_str("> \n");
    md.push_str("> **Confidence notation in this report**: `Extracted` edges are \
                 directly visible in the AST (class definitions, contains, import \
                 statements). `Inferred` edges are resolved by name-and-receiver \
                 lookup against the project's symbol index. `Ambiguous` edges had \
                 multiple candidate matches — treat them as hints only.\n\n");
    md.push_str("---\n\n");

    // ── Overview ──────────────────────────────────────────────────────────────
    md.push_str("## Overview\n\n");
    md.push_str("| Metric | Value |\n|---|---|\n");
    md.push_str(&format!("| Artifacts | {} |\n", map.node_count()));
    md.push_str(&format!("| Dependencies | {} |\n", map.edge_count()));
    md.push_str(&format!("| Modules | {} |\n", num_modules));
    md.push_str(&format!("| Hotspots | {} |\n", analysis.hotspots.len()));
    md.push_str(&format!(
        "| Cross-module couplings | {} |\n\n",
        analysis.couplings.len()
    ));

    // ── Architecture in one paragraph ─────────────────────────────────────────
    if num_modules > 0 {
        let mut sizes: Vec<(usize, &str, usize)> = (0..num_modules)
            .map(|i| (i, modules.name_of(i), modules.members[i].len()))
            .collect();
        sizes.sort_by(|a, b| b.2.cmp(&a.2));
        let top: Vec<String> = sizes
            .iter()
            .take(5)
            .map(|(_, name, sz)| format!("**{}** ({} artifacts)", name, sz))
            .collect();
        md.push_str("## Architecture at a Glance\n\n");
        md.push_str(&format!(
            "The codebase decomposes into **{} modules** detected by Leiden \
             community detection. The largest are {}. \
             Use the Modules section below for the full breakdown and the \
             Hotspots section for the most-connected individual artifacts.\n\n",
            num_modules,
            top.join(", ")
        ));
    }

    // ── Module breakdown ──────────────────────────────────────────────────────
    if num_modules > 0 {
        md.push_str("## Modules\n\n");
        md.push_str("Cohesive clusters of artifacts detected by community-finding on the dependency graph. \
                     Module names are derived from each cluster's dominant artifact.\n\n");

        let mut entries: Vec<(usize, &str, usize)> = (0..num_modules)
            .map(|i| (i, modules.name_of(i), modules.members[i].len()))
            .collect();
        entries.sort_by(|a, b| b.2.cmp(&a.2));

        for (i, name, size) in entries.iter().take(60) {
            md.push_str(&format!(
                "- **Module {}: `{}`** — {} artifacts\n",
                i, name, size
            ));
        }
        if entries.len() > 60 {
            md.push_str(&format!(
                "- … and {} smaller modules (see `grafly_knowledge.json` for the full list)\n",
                entries.len() - 60
            ));
        }
        md.push('\n');
    }

    // ── Hotspots ──────────────────────────────────────────────────────────────
    if !analysis.hotspots.is_empty() {
        md.push_str("## Hotspots\n\n");
        md.push_str("Artifacts whose degree is more than 2 standard deviations above the mean. \
                     These are likely architectural bottlenecks — components that many other \
                     parts of the codebase depend on. High hotspot degree often signals an \
                     opportunity to split responsibilities.\n\n");
        for h in analysis.hotspots.iter().take(30) {
            md.push_str(&format!(
                "- **`{}`** — {} connections (`{}`)\n",
                h.label, h.degree, h.source_file
            ));
        }
        if analysis.hotspots.len() > 30 {
            md.push_str(&format!(
                "- … and {} more hotspots\n",
                analysis.hotspots.len() - 30
            ));
        }
        md.push('\n');
    }

    // ── Cross-module couplings ────────────────────────────────────────────────
    if !analysis.couplings.is_empty() {
        md.push_str("## Cross-Module Couplings\n\n");
        md.push_str("Dependencies whose source and target belong to different modules. \
                     Each entry shows the relationship type and the exact source location \
                     (file:line) so you can trace it.\n\n");
        for c in analysis.couplings.iter().take(80) {
            md.push_str(&format!(
                "- `{}` → `{}` via **{}** (module {} → {}) — `{}:{}`\n",
                c.from_label,
                c.to_label,
                c.kind,
                c.from_module,
                c.to_module,
                c.source_file,
                c.source_line,
            ));
        }
        if analysis.couplings.len() > 80 {
            md.push_str(&format!(
                "- … and {} more couplings (see `grafly_knowledge.json`)\n",
                analysis.couplings.len() - 80
            ));
        }
        md.push('\n');
    }

    // ── Insights ──────────────────────────────────────────────────────────────
    if !analysis.insights.is_empty() {
        md.push_str("## Suggested Questions\n\n");
        md.push_str("These are starting points an LLM agent can use to drive architectural \
                     review or onboarding conversations. They were generated from graph \
                     structure, not LLM inference, so they're grounded in actual data.\n\n");
        for i in &analysis.insights {
            md.push_str(&format!("- {}\n", i));
        }
        md.push('\n');
    }

    md.push_str("---\n\n");
    md.push_str("*Generated by [grafly](https://grafly.net). \
                 Re-run `grafly <path>` to refresh.*\n");

    md
}

/// Generate the README.md that grafly writes alongside its output files.
///
/// This is the first thing an LLM agent (or human) encounters when they
/// open the output directory. It explains what each file is and what
/// questions each file is best suited to answer.
pub fn generate_output_readme() -> String {
    String::from(
        r#"# Grafly Output

> **For LLM agents**: this directory contains a precomputed analysis of the
> surrounding codebase, generated by [grafly](https://grafly.net). Read
> `grafly_report.md` first — it is the structured summary and points to the
> richer data in the JSON / HTML files when you need to drill in.

## What's in this directory

| File | Purpose | Use when… |
|---|---|---|
| `grafly_report.md` | Human + LLM-readable Markdown summary: modules, hotspots, cross-module couplings, suggested questions | Answering architectural and FAQ questions about the codebase |
| `grafly_knowledge.json` | Full directed dependency map — artifacts, dependencies, module assignments, source lines, confidence levels | Path-finding, neighbor queries, custom analysis, programmatic use |
| `grafly_modules.html` | Interactive module-level overview (modules as nodes, edges grouped by relationship kind) | Visualising the codebase's high-level shape |
| `grafly_artifacts.html` | Interactive artifact-level view (top-N artifacts by degree, Ambiguous edges suppressed) | Inspecting specific components and their immediate neighbourhood |

## How an LLM should use these files

1. **Start with `grafly_report.md`.** It's the curated view: a short
   "what is this codebase" summary plus the data needed to answer most
   architectural questions without ambiguity.
2. **Fall back to `grafly_knowledge.json`** when the user asks anything
   needing graph traversal — paths between components, who calls X, what
   depends on Y, transitive impact analysis, etc.
3. **Cite `source_file:source_line`** when explaining specific dependencies;
   every edge in the JSON carries them, and the Markdown report surfaces
   them on every cross-module coupling.
4. **Trust confidence labels.**
   - `Extracted` — directly in the AST. Believe it.
   - `Inferred` — resolved by receiver-aware name lookup. Usually correct.
   - `Ambiguous` — multiple candidates matched. Treat as a hint.

## How a human should use these files

Open `grafly_modules.html` in a browser for a bird's-eye view, or
`grafly_artifacts.html` for the detailed view. Read `grafly_report.md` for
the narrative summary.

## Schema (grafly_knowledge.json)

```json
{
  "artifacts": [
    {
      "id": "...",
      "label": "...",
      "kind": "File | Class | Struct | Enum | Interface | Trait | Function | Method | Namespace",
      "source_file": "...",
      "source_line": 1,
      "module_id": 0
    }
  ],
  "dependencies": [
    {
      "source": "<artifact id>",
      "target": "<artifact id>",
      "kind": "Contains | Imports | Calls | Extends | Implements | References",
      "confidence": "Extracted | Inferred | Ambiguous",
      "source_line": 1
    }
  ]
}
```
"#,
    )
}
